## Лабораторная работа №1 | Вариант 4

Выполнил: Колесник Дмитрий Сергеевич (М8О-313Б-23)

### 1. Numpy

In [3]:
import os
if not os.path.exists('ML'):
    !git clone https://github.com/DmitriyKolesnikM8O/ML.git

!pip install -q pandas numpy scikit-learn matplotlib seaborn

import numpy as np


Cloning into 'ML'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 24 (delta 3), reused 8 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (24/24), 507.33 KiB | 3.43 MiB/s, done.
Resolving deltas: 100% (3/3), done.


1. Найти индексы не нулевых элементов массива [1,2,0,0,4,0]

In [45]:
arr = [1, 2, 0, 0, 4, 0]
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)


2. Создайте единичную матрицу размером 3х3

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [9]:
minimal_square = [[1, 0], [0, 1]]
chess_matrix = np.tile(minimal_square, (4, 4))
print(chess_matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


4. Дан 1D массив, удалите все элементы которые входят в диапазон `[3, 8]` inplace

In [14]:
arr = [0, 4, 4, 2, 1, 4, 8, 7, 10, 15]
arr[:] = [x for x in arr if not (3 <= x <= 8)]
print(arr)

[0, 2, 1, 10, 15]


5. Создайте случайный вектор размером 10 элементов и замените максимальный элемент на 0

In [15]:
random_vec = np.random.rand(10)
print(random_vec)
random_vec[np.argmax(random_vec)] = 0
print(random_vec)

[0.96372444 0.44944212 0.48594394 0.078116   0.53294444 0.72706945
 0.19299839 0.15886437 0.29333858 0.37845182]
[0.         0.44944212 0.48594394 0.078116   0.53294444 0.72706945
 0.19299839 0.15886437 0.29333858 0.37845182]


6. Как распечатать все значения в массиве?

In [16]:
arr = np.arange(150)
# Можно обернуть в лист(list(arr))
# Можно в цикле пройтись просто (for element in arr: print(element))
# Можно настройки numpy изменить: np.set_printoptions(threshold=sys.maxsize)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), n

7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [28]:
coords = np.random.randint(0, 1000, size=(100, 2))
differences = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
squared_diffs = differences**2
sum_of_squares = squared_diffs.sum(axis=-1)
distance_matrix_numpy = np.sqrt(sum_of_squares)
print(distance_matrix_numpy[:10, :10])

[[   0.          657.46863043   72.11102551  303.59512513  461.9134118
   893.12261196  123.30855607  186.0376306   386.81907916  896.57124647]
 [ 657.46863043    0.          728.70913264  388.63479     282.79497874
   631.46575521  766.32238647  489.00408996  658.76399416  252.23996511]
 [  72.11102551  728.70913264    0.          367.76351097  532.66499791
   952.70772013   82.15229759  250.71497761  423.72278674  966.28774182]
 [ 303.59512513  388.63479     367.76351097    0.          312.02884482
   816.30999014  425.63951884  117.59251677  507.34702128  607.85031052]
 [ 461.9134118   282.79497874  532.66499791  312.02884482    0.
   504.84056889  546.80618138  349.01289374  376.37879855  530.64865966]
 [ 893.12261196  631.46575521  952.70772013  816.30999014  504.84056889
     0.          931.88250332  836.06339473  581.41637404  769.72982273]
 [ 123.30855607  766.32238647   82.15229759  425.63951884  546.80618138
   931.88250332    0.          308.42341027  377.4864236  1010.1113

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [41]:
float_arr = np.array([1.2, 2.8, 5.0, -3.7, 9.9], dtype=np.float32)
print(f"Исходный массив: {float_arr}")
print(f"ДО: {id(float_arr.data)}")
float_arr.view(np.int32)[:] = float_arr
print(f"\nРезультат (просмотренный как int32): {float_arr.view(np.int32)}")
print(f"ID ПОСЛЕ:   {id(float_arr.view(np.int32).data)}")


Исходный массив: [ 1.2  2.8  5.  -3.7  9.9]
ДО: 134039012310080

Результат (просмотренный как int32): [ 1  2  5 -3  9]
ID ПОСЛЕ:   134039012310080


9. Как прочитать заданный файл?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [44]:
import io

file = """1, 2, 3, 4, 5
6, , , 7, 8
, , 9,10,11
"""

data = np.genfromtxt(io.StringIO(file), delimiter=',')
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


10. Какой эквивалент enumerate для numpy массивов?

In [ ]:
# numpy.ndenumerate

### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом

Файл: `russian-housing-market.csv`

```
price_doc - Цена продажи
id - Id транзакции
timestamp - Дата транзакции
full_sq - суммарная площадь в квадратных метрах, включая лоджию, валконы и отдельные нежилые помещения
life_sq - жилая площаль в квадратных метрах, исключая лоджии, балконы и прочие нежилые помещения
floor - для апартаментов, этаж помещения
max_floor - количество этажей в здании
material - материал стен
build_year - год постройки
num_room - количество жилых комнат
kitch_sq - площадь кухни
state - состояние апартаментов
product_type - покупка или инвестиция собственника-арендатора
sub_area - название района
```

In [9]:
import pandas as pd

In [17]:
df = pd.read_csv('ML/hw1/russian-housing-market.csv')

id              30471
timestamp       30471
full_sq         30471
life_sq         24088
floor           30304
max_floor       20899
material        20899
build_year      16866
num_room        20899
kitch_sq        20899
state           16912
product_type    30471
sub_area        30471
price_doc       30471
dtype: int64

1. Посчитайте количество записей в датасете с отсутствующей информацией о жилой площади жилого помещения

In [11]:
missing_life_sq_count = df['life_sq'].isnull().sum()

Количество записей с отсутствующей информацией о жилой площади: 6383


2. Предложите способ заменить отсутствующие значения из пункта 1 и реализуйте его. Способ нужно аргументировать(сказать почему это достаточно хорошее приближение)

In [20]:
sane_data_mask = ((df['full_sq'] > 0) & (df['life_sq'].notna()) &
    (~np.isinf(df['life_sq'])) & (df['full_sq'] >= df['life_sq']))
sane_data = df[sane_data_mask]
avg_life_full_sq_ratio = (sane_data['life_sq'] / sane_data['full_sq']).mean()
imputed_values = df.loc[df['life_sq'].isnull(), 'full_sq'] * avg_life_full_sq_ratio
df['life_sq'] = df['life_sq'].fillna(imputed_values)
missing_after_fill = df['life_sq'].isnull().sum()

# Вместо заполнения условными 0 или еще чем-то, логично посчитать среднюю
# долю жилой площади от общей площади для тех помещений, где все нормально,
# и просто заполнить эти поля данными значениями. Так мы сможем сохранять
# общую пропорциональность

Средняя доля жилой площади от общей (финальный расчет): 0.6337

Количество пропусков (NaN) в 'life_sq' после замены: 0


3. Какие значения имеет 25, 50 и 75 перцентили полной площади помещения

In [21]:
full_sq_percentiles = df['full_sq'].quantile([0.25, 0.50, 0.75])
print(f"25-й перцентиль (Q1):   {full_sq_percentiles.loc[0.25]:.2f} кв.м.")
print(f"50-й перцентиль (Медиана): {full_sq_percentiles.loc[0.50]:.2f} кв.м.")
print(f"75-й перцентиль (Q3):   {full_sq_percentiles.loc[0.75]:.2f} кв.м.")

# 25: 38.00
# 50: 49.00
# 75: 63.00

Значения перцентилей для полной площади помещения (full_sq):
------------------------------------------------------------
25-й перцентиль (Q1):   38.00 кв.м.
50-й перцентиль (Медиана): 49.00 кв.м.
75-й перцентиль (Q3):   63.00 кв.м.


4. Посчитайте среднюю стоимость продажи помещений с общей площадью от 50 до 70 квадратных метров

In [24]:
square = (df['full_sq'] >= 50) & (df['full_sq'] <= 70)
filtered_prices = df.loc[square, 'price_doc']
average_price = filtered_prices.mean()
print(average_price)

7243041.190994609


5. Какая максимальная этажность здания представлена в датасете

In [26]:
max_building_floor = df['max_floor'].max()
print(max_building_floor)

117.0


6. Выявите район с самым дорогим жильем

In [28]:
median_prices = df.groupby('sub_area')['price_doc'].median()
most_expensive_block = median_prices.idxmax()
print(most_expensive_block)

Hamovniki


7. Посчитайте среднюю стоимость за квадратный метр жилья в Митино(Mitino)

In [34]:
mitino = df[df['sub_area'] == 'Mitino']
price_per_sq_meter = mitino['price_doc'] / mitino['full_sq']
average_price = price_per_sq_meter.mean()
print(average_price)

171841.39999559196


8. Посчитайте среднюю площадь комнаты в Бибирево

In [42]:
bibirevo_df = df[df['sub_area'] == 'Bibirevo']
avg_room_area_per_flat = bibirevo_df['life_sq'] / bibirevo_df['num_room']
overall_avg_room_area = avg_room_area_per_flat.mean()
print(overall_avg_room_area)

16.06687657275503


9. Проанализируйте есть ли разница в цене между квартирами на 1 и 9 этажах

In [45]:
first_floor = df[(df['floor'] == 1)]
ninth_floor = df[(df['floor'] == 9)]
median_price_sqm_1st = (first_floor['price_doc'] / first_floor['full_sq']).median()
median_price_sqm_9th = (ninth_floor['price_doc'] / ninth_floor['full_sq']).median()

price_difference_percent = ((median_price_sqm_9th - median_price_sqm_1st) / median_price_sqm_1st) * 100

if price_difference_percent > 0:
    print(f"9 этаж в среднем дороже на: {price_difference_percent:.2f}%")
elif price_difference_percent < 0:
    print(f"9 этаж в среднем дешевле на: {abs(price_difference_percent):.2f}%")
else:
    print("Шо то..., шо это....")

9 этаж в среднем дороже на: 2.99%


10. Найдите минимальную стоимость квартиры с жилой площадью не менее 60 квадратных метров, не менее чем 3мя комнатами и не ниже чем на 5 этаже

In [48]:
mask = (
    (df['life_sq'] >= 60) &
    (df['num_room'] >= 3) &
    (df['floor'] >= 5)
)
filtered_prices = df.loc[mask, 'price_doc']
min_price = filtered_prices.min()
if pd.notna(min_price):
    print(min_price)
else:
    print("Пока такое не построили")

1000000


### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Как менялась средняя цена квартиры в Нагатинском Затоне(Nagatinski Zaton) с течением времени

2. Постройте гистограмму распределения цен на квартиры с общей площадью более 50 кв.метров

3. Визуализируйте количество проданных квартир в разных районах

4. Постройте box plot отображающий распределение полных площадей квартир в Басманном районе

5. Визуализируйте зависимость средней стоимости квартир в зависимости от этажа

6. Покажите как меняется средняя площадь квартир в зависимости от района

7. Постройте график изменения медианной цены на квартиру менее 50 кв. метров за период с 2011 до 2014 года*

\* Задание на доп. балл