## Лабораторная работа №1 | Вариант 4

Выполнил: Колесник Дмитрий Сергеевич (М8О-313Б-23)

### 1. Numpy

In [7]:
import os
if not os.path.exists('ML'):
    !git clone https://github.com/DmitriyKolesnikM/ML.git

!pip install -q pandas numpy scikit-learn matplotlib seaborn

import numpy as np


Окружение настроено, данные загружены в переменную 'df'.
Последние 5 строк данных:


id   timestamp  full_sq  life_sq  floor  max_floor  material  \
30466  30469  2015-06-30       44     27.0    7.0        9.0       1.0   
30467  30470  2015-06-30       86     59.0    3.0        9.0       2.0   
30468  30471  2015-06-30       45      NaN   10.0       20.0       1.0   
30469  30472  2015-06-30       64     32.0    5.0       15.0       1.0   
30470  30473  2015-06-30       43     28.0    1.0        9.0       1.0   

       build_year  num_room  kitch_sq  state   product_type  \
30466      1975.0       2.0       6.0    3.0     Investment   
30467      1935.0       4.0      10.0    3.0     Investment   
30468         NaN       1.0       1.0    1.0  OwnerOccupier   
30469      2003.0       2.0      11.0    2.0     Investment   
30470      1968.0       2.0       6.0    2.0     Investment   

                   sub_area  price_doc  
30466              Otradnoe    7400000  
30467              Tverskoe   25000000  
30468  Poselenie Vnukovskoe    6970959  
30469          Obruchevskoe   13500000  
30470           Novogireevo    5600000

1. Найти индексы не нулевых элементов массива [1,2,0,0,4,0]

In [45]:
arr = [1, 2, 0, 0, 4, 0]
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)


2. Создайте единичную матрицу размером 3х3

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [9]:
minimal_square = [[1, 0], [0, 1]]
chess_matrix = np.tile(minimal_square, (4, 4))
print(chess_matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


4. Дан 1D массив, удалите все элементы которые входят в диапазон `[3, 8]` inplace

In [14]:
arr = [0, 4, 4, 2, 1, 4, 8, 7, 10, 15]
arr[:] = [x for x in arr if not (3 <= x <= 8)]
print(arr)

[0, 2, 1, 10, 15]


5. Создайте случайный вектор размером 10 элементов и замените максимальный элемент на 0

In [15]:
random_vec = np.random.rand(10)
print(random_vec)
random_vec[np.argmax(random_vec)] = 0
print(random_vec)

[0.96372444 0.44944212 0.48594394 0.078116   0.53294444 0.72706945
 0.19299839 0.15886437 0.29333858 0.37845182]
[0.         0.44944212 0.48594394 0.078116   0.53294444 0.72706945
 0.19299839 0.15886437 0.29333858 0.37845182]


6. Как распечатать все значения в массиве?

In [16]:
arr = np.arange(150)
# Можно обернуть в лист(list(arr))
# Можно в цикле пройтись просто (for element in arr: print(element))
# Можно настройки numpy изменить: np.set_printoptions(threshold=sys.maxsize)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), n

7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [28]:
coords = np.random.randint(0, 1000, size=(100, 2))
differences = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
squared_diffs = differences**2
sum_of_squares = squared_diffs.sum(axis=-1)
distance_matrix_numpy = np.sqrt(sum_of_squares)
print(distance_matrix_numpy[:10, :10])

[[   0.          657.46863043   72.11102551  303.59512513  461.9134118
   893.12261196  123.30855607  186.0376306   386.81907916  896.57124647]
 [ 657.46863043    0.          728.70913264  388.63479     282.79497874
   631.46575521  766.32238647  489.00408996  658.76399416  252.23996511]
 [  72.11102551  728.70913264    0.          367.76351097  532.66499791
   952.70772013   82.15229759  250.71497761  423.72278674  966.28774182]
 [ 303.59512513  388.63479     367.76351097    0.          312.02884482
   816.30999014  425.63951884  117.59251677  507.34702128  607.85031052]
 [ 461.9134118   282.79497874  532.66499791  312.02884482    0.
   504.84056889  546.80618138  349.01289374  376.37879855  530.64865966]
 [ 893.12261196  631.46575521  952.70772013  816.30999014  504.84056889
     0.          931.88250332  836.06339473  581.41637404  769.72982273]
 [ 123.30855607  766.32238647   82.15229759  425.63951884  546.80618138
   931.88250332    0.          308.42341027  377.4864236  1010.1113

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [41]:
float_arr = np.array([1.2, 2.8, 5.0, -3.7, 9.9], dtype=np.float32)
print(f"Исходный массив: {float_arr}")
print(f"ДО: {id(float_arr.data)}")
float_arr.view(np.int32)[:] = float_arr
print(f"\nРезультат (просмотренный как int32): {float_arr.view(np.int32)}")
print(f"ID ПОСЛЕ:   {id(float_arr.view(np.int32).data)}")


Исходный массив: [ 1.2  2.8  5.  -3.7  9.9]
ДО: 134039012310080

Результат (просмотренный как int32): [ 1  2  5 -3  9]
ID ПОСЛЕ:   134039012310080


9. Как прочитать заданный файл?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [44]:
import io

file = """1, 2, 3, 4, 5
6, , , 7, 8
, , 9,10,11
"""

data = np.genfromtxt(io.StringIO(file), delimiter=',')
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


10. Какой эквивалент enumerate для numpy массивов?

In [ ]:
# numpy.ndenumerate

### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом

Файл: `russian-housing-market.csv`

```
price_doc - Цена продажи
id - Id транзакции
timestamp - Дата транзакции
full_sq - суммарная площадь в квадратных метрах, включая лоджию, валконы и отдельные нежилые помещения
life_sq - жилая площаль в квадратных метрах, исключая лоджии, балконы и прочие нежилые помещения
floor - для апартаментов, этаж помещения
max_floor - количество этажей в здании
material - материал стен
build_year - год постройки
num_room - количество жилых комнат
kitch_sq - площадь кухни
state - состояние апартаментов
product_type - покупка или инвестиция собственника-арендатора
sub_area - название района
```

In [ ]:
import pandas as pd

In [ ]:
# Load dataset here

1. Посчитайте количество записей в датасете с отсутствующей информацией о жилой площади жилого помещения

2. Предложите способ заменить отсутствующие значения из пункта 1 и реализуйте его. Способ нужно аргументировать(сказать почему это достаточно хорошее приближение)

3. Какие значения имеет 25, 50 и 75 перцентили полной площади помещения

4. Посчитайте среднюю стоимость продажи помещений с общей площадью от 50 до 70 квадратных метров

5. Какая максимальная этажность здания представлена в датасете

6. Выявите район с самым дорогим жильем

7. Посчитайте среднюю стоимость за квадратный метр жилья в Митино(Mitino)

8. Посчитайте среднюю площадь комнаты в Бибирево

9. Проанализируйте есть ли разница в цене между квартирами на 1 и 9 этажах

10. Найдите минимальную стоимость квартиры с жилой площадью не менее 60 квадратных метров, не менее чем 3мя комнатами и не ниже чем на 5 этаже

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Как менялась средняя цена квартиры в Нагатинском Затоне(Nagatinski Zaton) с течением времени

2. Постройте гистограмму распределения цен на квартиры с общей площадью более 50 кв.метров

3. Визуализируйте количество проданных квартир в разных районах

4. Постройте box plot отображающий распределение полных площадей квартир в Басманном районе

5. Визуализируйте зависимость средней стоимости квартир в зависимости от этажа

6. Покажите как меняется средняя площадь квартир в зависимости от района

7. Постройте график изменения медианной цены на квартиру менее 50 кв. метров за период с 2011 до 2014 года*

\* Задание на доп. балл